services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_API_TOKEN}
    volumes:
      - ${INFLUX_DB_DATA_DIRECTORY}:/var/lib/influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - INFLUX_API_TOKEN=${INFLUX_API_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - BUCKET=${INFLUX_BUCKET}
    links:
      - influxdb
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/main.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/
  
  ftdc_exporter:
    build: ./ftdc_exporter
    volumes:
      - ${INPUT_DIR}:/diagnostic.data
      - ./metrics_to_get.txt:/app/metrics_to_get.txt
    depends_on:
      influxdb:
        condition: service_healthy
    command: >
      ./ftdc_exporter
       --input-dir /diagnostic.data
       --metrics-include-file /app/metrics_to_get.txt
       --influx-url http://influxdb:8086
       --influx-token ${INFLUX_API_TOKEN}
       --influx-org ${INFLUX_ORG}
       --influx-bucket ${INFLUX_BUCKET}
       --parallel ${PARALLEL}
       --batch-size ${BATCH_SIZE}
volumes:
  influxdb-data:
